{% set version="1.3.0.20181218191458" %}
package:
  name: arvados-cwl-runner
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b7/26/f83564ba9bb85bbae289ad5e7a4010904654c0d834c52ef5d5387856ad27/arvados-cwl-runner-{{ version }}.tar.gz
  sha256: f7fdb3a357ccac03e5a55fc99290f7f2297eaaac6a91e35b8fb0270ef9de3767

build:
  number: 0
  skip: True # [not py27]

requirements:
  host:
    - python
    - setuptools
    - ruamel.yaml >=0.13.7,<0.15
    - cwltool >=1.0.20180130110340
    - schema-salad >=2.6.20171201034858
    - arvados-python-client >=0.1.20171211211613

  run:
    - python
    - ruamel.yaml >=0.13.7,<0.15
    - cwltool >=1.0.20180130110340
    - schema-salad >=2.6.20171201034858
    - arvados-python-client >=0.1.20171211211613

test:
  imports:
    - arvados_cwl

  # Needs connection to Arvados server to run help
  #commands:
  #  - arvados-cwl-runner --help

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/cwl
  license: Apache 2.0
  summary: 'Arvados Common Workflow Language runner'
