{% set version ="1.0" %}

package:
 name: crispr-studio
 version: {{ version }}

source:
 url: https://github.com/moineaulab/CRISPRStudio/archive/v1.tar.gz
 sha256: 23cb08bdb851c473ba6275e40e9fdd9aedcb6590d1f53cc04cae776fb39e2fa8

build:
 number: 0 
 entry_points:
  - crispr-studio = CRISPR_Studio:main

requirements:
 host:
  - python
 run:
  - python 3
  - scipy
  - numpy
  - pandas
 
test:
 commands:
  - cd ../work_moved_crispr-studio-1.0-py36_0_linux-64
  - pip install scipy numpy pandas scikit-bio
  - ./CRISPR_Studio -h


about:
 home: https://github.com/moineaulab/CRISPRStudio
 license: GPL-3.0
 license_file: LICENSE
 summary: CRISPRStudio is a program developed to facilitate and accelerate CRISPR array visualization
